import { DEFAULT_COLUMNS } from '@/lib/utils/defaults'

export const HOME_CURSOR_RESULT_INDEX = 3
export const FOOTER_LINK_COUNT = 4

export const DEFAULT_FOCUS_FREQUENCY = DEFAULT_COLUMNS[1]
export const DEFAULT_FOCUS_TIME_SAVED_SECONDS = 60

export const HOME_STAGE_STAGGER_MS = 90
export const HOME_REVEAL_STAGE_RESULT = 1
export const HOME_REVEAL_STAGE_SHOW_TABLE = 2
export const HOME_REVEAL_STAGE_KEY_COMMANDS = 3
export const HOME_REVEAL_STAGE_FOOTER_START = 4
export const HOME_RESULT_TYPEWRITER_DURATION_MS = 260
export const HOME_SHOW_TABLE_TYPEWRITER_DURATION_MS = 280
export const HOME_KEY_COMMANDS_TO_FOOTER_DELAY_MS = 760
export const HOME_KEY_COMMANDS_LINK_TO_FOOTER_DELAY_MS = 220
export const HOME_SHOW_TABLE_LABEL = 'Show full table 🡪'
