export const SECONDS_IN_MINUTE = 60
export const SECONDS_IN_HOUR = 60 * SECONDS_IN_MINUTE
export const SECONDS_IN_DAY = 24 * SECONDS_IN_HOUR
export const SECONDS_IN_WEEK = 7 * SECONDS_IN_DAY
export const SECONDS_IN_MONTH = 30.4375 * SECONDS_IN_DAY
export const SECONDS_IN_YEAR = 365.25 * SECONDS_IN_DAY

export const PARSER_YEAR_SECONDS = 365 * 24 * 60 * 60

export const SUSPICIOUS_SECONDS_THRESHOLD = 10 * SECONDS_IN_YEAR
